# Generated by Django 5.0.1 on 2024-02-14 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfield',
            name='log',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logs.log'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logfield',
            name='log_value',
            field=models.TextField(),
        ),
    ]
